name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies for ChromeDriver script
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip jq

          # Fetch correct Chrome for Testing version (raw text, no HTML)
          LATEST=$(curl -s https://raw.githubusercontent.com/GoogleChromeLabs/chrome-for-testing/refs/heads/main/LATEST_RELEASE)

          echo "Using Chrome for Testing version: $LATEST"

          # Download Chrome for Testing
          wget https://storage.googleapis.com/chrome-for-testing-public/$LATEST/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64 /opt/chrome

          # Download ChromeDriver
          wget https://storage.googleapis.com/chrome-for-testing-public/$LATEST/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-behave

      - name: Run tests with Behave
        run: |
          chmod +x scripts/run_behave.sh
          ./scripts/run_behave.sh

      - name: Generate Allure HTML report
        run: |
          chmod +x scripts/generate_allure_report.sh
          ./scripts/generate_allure_report.sh

      - name: Upload results folder
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: results/
